=== MBala98/ewp-specs-api-omobility-las-stats-endpoint/endpoints/stats-response.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"

    targetNamespace="https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/stable-v1/endpoints/stats-response.xsd"
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/stable-v1/endpoints/stats-response.xsd"
>
    <xs:annotation>
        <xs:documentation>
            This schema is a part of the Erasmus Without Paper project. Before you start
            using it, make sure you have read the general rules described here:

            http://developers.erasmuswithoutpaper.eu/
        </xs:documentation>
    </xs:annotation>

    <xs:element name="las-outgoing-stats-response">
        <xs:complexType>
            <xs:sequence>
               <xs:element name="academic-year-la-stats" minOccurs="1" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            This element represents a single academic year by which Learning Agreements are grouped.
                            It contains a list of statistics for the specified year.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="year" type="xs:string"> <!-- TODO: change type to custom year?-->
                                <xs:annotation>
                                    <xs:documentation>
                                        The year for which statistics are specified.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="la-sum" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Numer of incoming LAs
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="la-single-version-approved" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        (only before the mobility) Number outgoing LAs with one version approved by the receiving HEI
                                        which has not been followed by any other version.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="la-at-least-one-approved" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of incoming LAs with at least one version approved by the receiving HEI.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="la-latest-approved" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of incoming LAs with the latest version approved by the receiving HEI.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>

                            <xs:element name="la-latest-rejected" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of incoming LAs with the latest version rejected by the receiving HEI.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>

                            <xs:element name="la-latest-awaiting" type="xs:integer">
                                <xs:annotation>
                                    <xs:documentation>
                                        Number of incoming LAs with the latest version awaiting receiving HEIâ€™s approval.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

    </xs:element>
</xs:schema>

=== MBala98/ewp-specs-api-omobility-las-stats-endpoint/endpoints/stats-response-example.xml
<las-outgoing-stats-response
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/stable-v1/endpoints/stats-response.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/stable-v1/endpoints/stats-response.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/stable-v1/endpoints/stats-response.xsd
    "
>

   <academic-year-la-stats>
        <year>2020</year>
        <la-sum>0</la-sum>
        <la-single-version-approved>0</la-single-version-approved>
        <la-at-least-one-approved>0</la-at-least-one-approved>
        <la-latest-approved>0</la-latest-approved>
        <la-latest-rejected>0</la-latest-rejected>
        <la-latest-awaiting>0</la-latest-awaiting>
    </academic-year-la-stats>

        <academic-year-la-stats>
        <year>2021</year>
        <la-sum>0</la-sum>
        <la-single-version-approved>0</la-single-version-approved>
        <la-at-least-one-approved>0</la-at-least-one-approved>
        <la-latest-approved>0</la-latest-approved>
        <la-latest-rejected>0</la-latest-rejected>
        <la-latest-awaiting>0</la-latest-awaiting>
    </academic-year-la-stats>

</las-outgoing-stats-response>
